#!/usr/bin/env bun
import { builtinModules } from "node:module";
import {
	appendFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	statSync,
	symlinkSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { resolve } from "node:path";
import { build, type ServerWebSocket } from "bun";
import { watch } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/
`;

const command = process.argv[2];
const isProd = command === "production";
const isInstall = command === "install";
const isClean = command === "clean";
const HOT_RELOAD_PORT = 2772;

// Read plugin ID from manifest for CLI reload
const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
const pluginId = manifest.id;

const config = {
	entrypoints: ["src/main.ts"],
	outdir: ".",
	target: "browser" as const,
	format: "cjs" as const,
	minify: isProd,
	sourcemap: isProd ? ("none" as const) : ("inline" as const),
	banner,
	naming: { entry: "main.js" },
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
};

const STYLE_SOURCES = [
	"src/styles.css",
	"src/styles/view.css",
	"src/styles/gallery-toolbar.css",
	"src/styles/gallery-grid.css",
	"src/styles/gallery-cards.css",
	"src/styles/detail-view.css",
	"src/styles/token-editors.css",
	"src/styles/schema-modal.css",
	"src/styles/utilities.css",
	"src/styles/responsive.css",
] as const;

// --- Hot reload strategies ---

function hasObsidianCli(): boolean {
	return Bun.which("obsidian") !== null;
}

function createCliReloader(): () => void {
	console.log(`Hot reload via Obsidian CLI (plugin:reload id=${pluginId})`);
	return () => {
		Bun.spawn(["obsidian", "plugin:reload", `id=${pluginId}`], {
			stdout: "ignore",
			stderr: "ignore",
		});
	};
}

const wsHotReloadSnippet = `
;(function() {
	var OrigPlugin = module.exports.default || module.exports;
	var origOnload = OrigPlugin.prototype.onload;
	OrigPlugin.prototype.onload = function() {
		var plugin = this;
		var ws = new WebSocket("ws://127.0.0.1:${HOT_RELOAD_PORT}");
		ws.onmessage = function() {
			var plugins = plugin.app.plugins;
			var id = plugin.manifest.id;
			plugins.disablePlugin(id).then(function() { plugins.enablePlugin(id); });
		};
		ws.onerror = function() { ws.close(); };
		plugin.register(function() { ws.close(); });
		return origOnload.call(this);
	};
})();
`;

function createWsReloader(): () => void {
	const clients = new Set<ServerWebSocket>();

	Bun.serve({
		port: HOT_RELOAD_PORT,
		fetch(req, server) {
			if (server.upgrade(req)) return;
			return new Response(null, { status: 426 });
		},
		websocket: {
			open(ws) {
				clients.add(ws);
			},
			close(ws) {
				clients.delete(ws);
			},
			message() {},
		},
	});

	console.log(
		`Hot reload via WebSocket fallback (ws://localhost:${HOT_RELOAD_PORT})`,
	);
	console.log(
		"Tip: install the Obsidian CLI for a cleaner hot-reload experience:",
	);
	console.log("  https://help.obsidian.md/cli");

	return () => {
		for (const client of clients) {
			client.send("reload");
		}
	};
}

// --- Build ---

let useWsFallback = false;

function buildStyles() {
	const parts = STYLE_SOURCES.map((path) => {
		if (!existsSync(path)) {
			throw new Error(`Missing style source: ${path}`);
		}

		return `/* ${path} */\n${readFileSync(path, "utf8").trimEnd()}`;
	});

	writeFileSync("styles.css", `${parts.join("\n\n")}\n`);
}

function notifyBuildError(hasCli: boolean) {
	console.error("Build failed!");
	if (hasCli) {
		Bun.spawn(
			["obsidian", "eval", 'code=new Notice("Build failed — check terminal")'],
			{ stdout: "ignore", stderr: "ignore" },
		);
	}
}

async function buildPlugin(): Promise<boolean> {
	const start = performance.now();
	const result = await build(config);

	if (!result.success) {
		console.error("Build failed:");
		result.logs.forEach((log) => console.error(log));
		return false;
	}

	try {
		buildStyles();
	} catch (error) {
		console.error(error);
		return false;
	}

	if (!isProd && useWsFallback) {
		appendFileSync("main.js", wsHotReloadSnippet);
	}

	const elapsed = (performance.now() - start).toFixed(0);
	const size = (statSync("main.js").size / 1024).toFixed(1);
	console.log(`Built in ${elapsed}ms (${size} kB)`);
	return true;
}

// --- Vault install ---

function installToVault(vaultPath: string) {
	const pluginDir = resolve(vaultPath, ".obsidian", "plugins", pluginId);
	const projectDir = resolve(".");

	if (existsSync(pluginDir)) {
		console.log(`Plugin directory already exists: ${pluginDir}`);
		console.log("Remove it first if you want to re-link.");
		process.exit(1);
	}

	mkdirSync(resolve(vaultPath, ".obsidian", "plugins"), { recursive: true });
	symlinkSync(projectDir, pluginDir);
	console.log(`Symlinked: ${pluginDir} → ${projectDir}`);
	console.log(
		"Restart Obsidian and enable the plugin in Settings → Community plugins.",
	);
}

// --- Watcher ---

function startWatcher(notifyReload: () => void, hasCli: boolean) {
	console.log("Watching for changes...");
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;

	watch("src", { recursive: true }, (_, filename) => {
		if (!filename) return;
		if (!filename.endsWith(".ts") && !filename.endsWith(".css")) return;

		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(async () => {
			console.log(`File changed: ${filename}`);

			try {
				const ok = await buildPlugin();
				if (ok) {
					notifyReload();
				} else {
					notifyBuildError(hasCli);
				}
			} catch (error) {
				console.error("Rebuild failed:", error);
				notifyBuildError(hasCli);
			}
		}, 100);
	});
}

// --- Main ---

function cleanArtifacts() {
	for (const file of ["main.js", "styles.css"]) {
		try {
			unlinkSync(file);
		} catch {}
	}
	console.log("Cleaned build artifacts.");
}

async function main() {
	if (isClean) {
		cleanArtifacts();
		return;
	}

	if (isInstall) {
		const vaultPath = process.argv[3] || process.env.OBSIDIAN_VAULT;
		if (!vaultPath) {
			console.error("Usage: bun run dev:install <vault-path>");
			console.error("   or: set OBSIDIAN_VAULT in .env");
			console.error("Example: bun run dev:install ~/Documents/MyVault");
			process.exit(1);
		}
		installToVault(vaultPath);
		return;
	}

	const hasCli = !isProd && hasObsidianCli();

	if (!isProd) {
		useWsFallback = !hasCli;
	}

	const ok = await buildPlugin();
	if (!ok) {
		process.exit(1);
	}

	if (!isProd) {
		const pluginDir = resolve(".obsidian", "plugins", pluginId);
		const isLinked =
			existsSync(pluginDir) || process.env.OBSIDIAN_VAULT || hasCli;
		if (!isLinked) {
			console.log("");
			console.log("Tip: link this plugin to a vault for hot reload:");
			console.log("  bun run dev:install ~/path/to/your/vault");
		}

		const notifyReload = hasCli ? createCliReloader() : createWsReloader();
		startWatcher(notifyReload, hasCli);
	}
}

main();
